apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: url-shortener-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "watch", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: url-shortener-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: url-shortener-sa
    namespace: default
roleRef:
  kind: Role
  name: url-shortener-role
  apiGroup: rbac.authorization.k8s.io