apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secret
  namespace: url-shortener
  annotations:
    kubernetes.io/service-account.name: url-shortener-service-account
type: kubernetes.io/service-account-token